/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as ApiPublicWhatsappFlowRouteImport } from './routes/api/public/whatsapp-flow'
import { Route as AuthenticatedTripsNewRouteImport } from './routes/_authenticated/trips.new'
import { Route as AuthenticatedTripsTripIdIndexRouteImport } from './routes/_authenticated/trips.$tripId.index'
import { Route as AuthenticatedTripsTripIdReportRouteImport } from './routes/_authenticated/trips.$tripId.report'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWhatsappFlowRoute = ApiPublicWhatsappFlowRouteImport.update({
  id: '/api/public/whatsapp-flow',
  path: '/api/public/whatsapp-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsNewRoute = AuthenticatedTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsTripIdIndexRoute =
  AuthenticatedTripsTripIdIndexRouteImport.update({
    id: '/trips/$tripId/',
    path: '/trips/$tripId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTripsTripIdReportRoute =
  AuthenticatedTripsTripIdReportRouteImport.update({
    id: '/trips/$tripId/report',
    path: '/trips/$tripId/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/api/public/whatsapp-flow': typeof ApiPublicWhatsappFlowRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/trips/$tripId/': typeof AuthenticatedTripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/api/public/whatsapp-flow': typeof ApiPublicWhatsappFlowRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/trips/new': typeof AuthenticatedTripsNewRoute
  '/api/public/whatsapp-flow': typeof ApiPublicWhatsappFlowRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/_authenticated/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/_authenticated/trips/$tripId/': typeof AuthenticatedTripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/manager'
    | '/trips/new'
    | '/api/public/whatsapp-flow'
    | '/trips/'
    | '/trips/$tripId/report'
    | '/trips/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/manager'
    | '/trips/new'
    | '/api/public/whatsapp-flow'
    | '/trips'
    | '/trips/$tripId/report'
    | '/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/manager'
    | '/_authenticated/trips/new'
    | '/api/public/whatsapp-flow'
    | '/_authenticated/trips/'
    | '/_authenticated/trips/$tripId/report'
    | '/_authenticated/trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWhatsappFlowRoute: typeof ApiPublicWhatsappFlowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp-flow': {
      id: '/api/public/whatsapp-flow'
      path: '/api/public/whatsapp-flow'
      fullPath: '/api/public/whatsapp-flow'
      preLoaderRoute: typeof ApiPublicWhatsappFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/new': {
      id: '/_authenticated/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthenticatedTripsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/$tripId/': {
      id: '/_authenticated/trips/$tripId/'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId/'
      preLoaderRoute: typeof AuthenticatedTripsTripIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/$tripId/report': {
      id: '/_authenticated/trips/$tripId/report'
      path: '/trips/$tripId/report'
      fullPath: '/trips/$tripId/report'
      preLoaderRoute: typeof AuthenticatedTripsTripIdReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedTripsNewRoute: typeof AuthenticatedTripsNewRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
  AuthenticatedTripsTripIdReportRoute: typeof AuthenticatedTripsTripIdReportRoute
  AuthenticatedTripsTripIdIndexRoute: typeof AuthenticatedTripsTripIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedTripsNewRoute: AuthenticatedTripsNewRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
  AuthenticatedTripsTripIdReportRoute: AuthenticatedTripsTripIdReportRoute,
  AuthenticatedTripsTripIdIndexRoute: AuthenticatedTripsTripIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWhatsappFlowRoute: ApiPublicWhatsappFlowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
